---
# tasks file for flask_web
- name: Install flask
  pip:
    name: "{{item }}"
    state: present
  with_items:
  - flask
  - flask-mysql
- name: copy the web server code
  copy: src=app.py dest=/opt/app.py
- name: start the web application
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
